world:
  env_name: ALE/Pong-v5
  num_envs: 1
  image_shape: [224, 160]
  goal_conditioned: false
  render_mode: rgb_array

  # We want one environment step to equal one emulator frame.
  # Temporal abstraction is handled later by the SWM Dataset.
  frameskip: 1

  # Deterministic dynamics are easier for our first world-model baseline.
  repeat_action_probability: 0.0

  # Use Pong's meaningful 6-action subset instead of all 18 Atari actions.
  full_action_space: false

  # Fixed trajectory horizon for our training dataset.
  max_episode_steps: 1000


policy:
  seed: 42


collection:
  path: ${oc.env:STABLEWM_HOME}/datasets/pong_random.lance

  episodes: 100
  seed: 42

  format: lance
  mode: overwrite